### ISSUE TITLE
Couldn't download the dunbrak_rotamer library

### ISSUE THREAD

**Issue by ybwu01** [facebookresearch/protein-ebm#1]
It seems that the link ( https://dl.fbaipublicfiles.com/protein-ebm/dunbrak_rotamer.tar.gz) is invalid. Could you double check it?  Many thanks.

**Comment by joshim5** [comment]
The correct link is s3://dl.fbaipublicfiles.com/protein-ebm/dunbrack_rotamer.tar.gz.
The typo is fixed in PR #2. Thanks for reporting!
